version: '3.8'

services:
  engine_builder:
    build:
      context: ./engine
      dockerfile: Dockerfile.wasm
    volumes:
      - ./client/public/wasm:/out
    command: /bin/sh -c "cp build_wasm/pawngo_wasm.* /out/"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://pawngo-api.mybsu.online 
    ports:
      - "5175:80"
    restart: always

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./engine/3-4-5:/app/syzygy
    restart: always